name: Django CI

on:
  workflow_dispatch:
  push:
    branches: [ "github_actions_experimentation" ]
  pull_request:
    branches: [ "github_actions_experimentation" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./config/requirements.txt
    - name: Create ENVARS
      run: |
        source ./config/settings_localdev_env.sh
    - name: Run Tests
      run: |
        python manage.py test
